name: flutter_build
description: A CLI tool that helps to build apps.
repository: https://github.com/fluttercandies/flutter_app_build_tool
version: 1.0.0

environment:
  sdk: ^2.17.0

dependencies:
  archive: ^3.3.7
  args: ^2.3.1
  built_collection: ^5.1.1
  collection: ^1.17.0
  code_builder: ^4.4.0
  crypto: ^3.0.2
  dart_style: ^2.2.5
  intl: '>=0.17.0 <1.0.0'
  path: ^1.8.3
  process_run: '>=0.12.3 <0.14.0'
  yaml: ^3.1.1

dev_dependencies:
  lints: any

executables:
  flutter_build: flutter_build
